### ISSUE TITLE
Sending commands to Minetest, and receiving chat messages

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/minetest_web_panel#1]
- Abstraction so that most of the code doesn't care how messages are sent to Minetest, or received.
- minetest.MinetestProcess will have a send() function
## Methods
- Sockets
- Writing to file, Minetest reading from file.
- Receiving messages can be done by reading debug log.
- Get/Post

**Comment by ShadowNinja** [comment]
Sockets will still work after security, you'll just have to add the mod to `secure.trusted_mods`.
